docker/Dockerfile: unbreak manual builds by pulling in docbook-xsl
Manual builds started breaking on 27/09 with an error from xsltproc:

a2x: ERROR: "xsltproc" --stringparam toc.section.depth 1 --stringparam
     callout.graphics 0 --stringparam navig.graphics 0 --stringparam
     admon.textlabel 1 --stringparam admon.graphics 0 --stringparam
     chunk.section.depth 0 --output "/output/docs/manual/manual.html"
     "/etc/asciidoc/docbook-xsl/xhtml.xsl" "/output/docs/manual/manual.xml"
returned non-zero exit status 5
make: *** [docs/manual/manual.mk:12: /output/docs/manual/manual.html] Error 1

Investigating further, it tries to reach out to sourceforge to fetch a
stylesheet and fails:

warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl"
compilation error: file /etc/asciidoc/docbook-xsl/text.xsl line 14 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl

Interesting enough, this doesn't happen on a "full" Debian installation.
Turns out that docbook-xsl (or one of its dependencies) is now needed.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>